CREATE TABLE IF NOT EXISTS reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    table_id BIGINT NOT NULL,
    customer_name CHARACTER VARYING(255),
    customer_email CHARACTER VARYING(255),
    customer_phone CHARACTER VARYING(255),
    reservation_date DATE NOT NULL,
    reservation_time TIME NOT NULL,
    number_of_people INT NOT NULL,
    status CHARACTER VARYING(20) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    PRIMARY KEY(id)
);